ciqual:
    resource: "@CiqualBundle/Controller/"
    type:     annotation
    prefix:   /cirqual

api:
    resource: '.'
    type:     'api_platform'
    prefix:   /api

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"