# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    ciqual.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', ORIGGPFR: 'exact', ORIGFDCD: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'ciqual.search' } ]

    ciqual.search_name_filter:
            parent:    'api_platform.doctrine.orm.search_filter'
            arguments: [ { ORIGFDNM: 'partial' } ]
            tags:      [ { name: 'api_platform.filter', id: 'ciqual.search.name' } ]
